bt_navigator:
  ros__parameters:
    # use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /localization/pose_twist_fusion_filter/ekf_odom
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    default_nav_through_poses_bt_xml: "/home/tsukutsuku/autoware/src/tsukutsuku/tsukutsuku2_bringup/config/nav2/navigate_through_poses_tsukutsuku.xml"
    default_nav_to_pose_bt_xml: "/home/tsukutsuku/autoware/src/tsukutsuku/tsukutsuku2_bringup/config/nav2/navigate_to_pose_tsukutsuku.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node

# bt_navigator_rclcpp_node:
#   ros__parameters:
#     use_sim_time: True

controller_server:
  ros__parameters:
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.2
    min_y_velocity_threshold: 0.2
    min_theta_velocity_threshold: 0.2
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]
    odom_topic: /localization/pose_twist_fusion_filter/ekf_odom

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.25
      movement_time_allowance: 60.0
    # Goal checker parameters
        #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5
      yaw_goal_tolerance: 0.4363 #25 deg
    
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 1.4
      max_vel_y: 1.4
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 1.4
      min_speed_theta: 0.5
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 1.0
      acc_lim_y: 0.0
      acc_lim_theta: 1.0
      decel_lim_x: -1.0
      decel_lim_y: 0.0
      decel_lim_theta: -1.0
      vx_samples: 50
      vy_samples: 20
      vtheta_samples: 50
      sim_time: 1.0
      linear_granularity: 0.1
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      # critics: ["ObstacleFootprint", "PathAlign", "GoalAlign"]
      critics: ["ObstacleFootprint", "PathAlign", "PathDist", "GoalAlign", "GoalDist"]
      BaseObstacle.scale: 0.01
      BaseObstacle.sum_scores: false
      ObstacleFootprint.scale: 0.001 
      ObstacleFootprint.sum_scores: false
      PathAlign.scale: 24.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 12.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 24.0
      GoalDist.scale: 12.0
      # RotateToGoal.scale: 24.0
      # RotateToGoal.slowing_factor: 5.0
      # RotateToGoal.lookahead_time: -1.0
      # PreferForward.scale: 32.0

# controller_server_rclcpp_node:
#   ros__parameters:
#     use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0 #Hz
      publish_frequency: 10.0 #Hz
      global_frame: map
      robot_base_frame: base_link
      # use_sim_time: True
      rolling_window: true
      width: 20
      height: 20
      lethal_cost_threshold: 65
      resolution: 0.05
      footprint: '[ [0.9, 0.33], [-0.2, 0.33], [-0.2, -0.33], [0.9, -0.33] ]'
      footprint_padding: 0.03
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        max_obstacle_height: 30.0
        min_obstacle_height: -30.0
        observation_sources: front_left_urg front_right_urg rear_urg
        front_left_urg:
          topic: /sensing/lidar/front_left_urg/scan
          max_obstacle_height: 15.0
          min_obstacle_height: -15.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 15.0
          raytrace_min_range: 0.0
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
        front_right_urg:
          topic: /sensing/lidar/front_right_urg/scan
          max_obstacle_height: 15.0
          min_obstacle_height: -15.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 15.0
          raytrace_min_range: 0.0
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
        rear_urg:
          topic: /sensing/lidar/rear_urg/scan
          max_obstacle_height: 15.0
          min_obstacle_height: -15.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          expected_update_rate: 40.0
          raytrace_max_range: 15.0
          raytrace_min_range: 0.0
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.15
      always_send_full_costmap: True
  # local_costmap_client:
  #   ros__parameters:
  #     use_sim_time: True
  # local_costmap_rclcpp_node:
  #   ros__parameters:
  #     use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 3.0
      publish_frequency: 3.0
      global_frame: map
      robot_base_frame: base_link
      footprint: '[ [0.9, 0.33], [-0.2, 0.33], [-0.2, -0.33], [0.9, -0.33] ]'
      footprint_padding: 0.03
      resolution: 0.3
      track_unknown_space: true
      always_send_full_costmap: True
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.1
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: True
        observation_sources: front_left_urg front_right_urg rear_urg 
        front_left_urg:
          topic: /sensing/lidar/front_left_urg/scan
          max_obstacle_height: 15.0
          min_obstacle_height: -15.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 15.0
          raytrace_min_range: 0.0
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
        front_right_urg:
          topic: /sensing/lidar/front_right_urg/scan
          max_obstacle_height: 15.0
          min_obstacle_height: -15.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 15.0
          raytrace_min_range: 0.0
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
        rear_urg:
          topic: /sensing/lidar/rear_urg/scan
          max_obstacle_height: 15.0
          min_obstacle_height: -15.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          expected_update_rate: 40.0
          raytrace_max_range: 15.0
          raytrace_min_range: 0.0
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0

map_server:
  ros__parameters:
    yaml_filename: ""

map_saver:
  ros__parameters:
    save_map_timeout: 500.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.125
      max_planning_time: 1.0
      allow_unknown: true
      smoother:
        max_iterations: 1000
        w_smooth: 0.8
        w_data: 0.2
        tolerance: 0.01

# planner_server_rclcpp_node:
#   ros__parameters:
#     use_sim_time: True

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["wait", "backup", "spin"]
    wait:
      plugin: "nav2_recoveries/Wait"
    backup:
      plugin: "nav2_recoveries/BackUp"
    spin:
      plugin: "nav2_recoveries/Spin"
    global_frame: map
    robot_base_frame: base_link
    transform_timeout: 0.1
    simulate_ahead_time: 2.0

# robot_state_publisher:
#   ros__parameters:
#     use_sim_time: True
    
waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200
