speed_filter_info_server:
  ros__parameters:
    use_sim_time: true
    type: 1  # Speed Filterのタイプ
    filter_info_topic: "/speed_filter_info"
    mask_topic: "/speed_filter_mask"
    base: 100.0
    multiplier: -1.0

speed_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    topic_name: "/speed_filter_mask"
    yaml_filename: ""